allowBuilds:
  esbuild: true
  lefthook: true
  msw: true
  vue-demi: true
minimumReleaseAgeExclude:
  - lefthook-darwin-arm64@2.1.12
  - lefthook-darwin-x64@2.1.12
  - lefthook-freebsd-arm64@2.1.12
  - lefthook-freebsd-x64@2.1.12
  - lefthook-linux-arm64@2.1.12
  - lefthook-linux-x64@2.1.12
  - lefthook-openbsd-arm64@2.1.12
  - lefthook-openbsd-x64@2.1.12
  - lefthook-windows-arm64@2.1.12
  - lefthook-windows-x64@2.1.12
  - lefthook@2.1.12
  - '@biomejs/biome@2.5.12'
  - '@biomejs/cli-darwin-arm64@2.5.12'
  - '@biomejs/cli-darwin-x64@2.5.12'
  - '@biomejs/cli-linux-arm64-musl@2.5.12'
  - '@biomejs/cli-linux-arm64@2.5.12'
  - '@biomejs/cli-linux-x64-musl@2.5.12'
  - '@biomejs/cli-linux-x64@2.5.12'
  - '@biomejs/cli-win32-arm64@2.5.12'
  - '@biomejs/cli-win32-x64@2.5.12'
  - '@vitest/coverage-v8@5.0.0'
  - '@vitest/mocker@5.0.0'
  - '@vitest/pretty-format@5.0.0'
  - '@vitest/spy@5.0.0'
  - '@vitest/ui@5.0.0'
  - '@vitest/utils@5.0.0'
  - vitest@5.0.0
