allowBuilds:
  esbuild: true
  lefthook: true
  msw: true
  vue-demi: true
minimumReleaseAgeExclude:
  - lefthook-darwin-arm64@2.1.12 || 2.1.16
  - lefthook-darwin-x64@2.1.12 || 2.1.16
  - lefthook-freebsd-arm64@2.1.12 || 2.1.16
  - lefthook-freebsd-x64@2.1.12 || 2.1.16
  - lefthook-linux-arm64@2.1.12 || 2.1.16
  - lefthook-linux-x64@2.1.12 || 2.1.16
  - lefthook-openbsd-arm64@2.1.12 || 2.1.16
  - lefthook-openbsd-x64@2.1.12 || 2.1.16
  - lefthook-windows-arm64@2.1.12 || 2.1.16
  - lefthook-windows-x64@2.1.12 || 2.1.16
  - lefthook@2.1.12 || 2.1.16
  - '@biomejs/biome@2.5.12 || 2.5.15'
  - '@biomejs/cli-darwin-arm64@2.5.12 || 2.5.15'
  - '@biomejs/cli-darwin-x64@2.5.12 || 2.5.15'
  - '@biomejs/cli-linux-arm64-musl@2.5.12 || 2.5.15'
  - '@biomejs/cli-linux-arm64@2.5.12 || 2.5.15'
  - '@biomejs/cli-linux-x64-musl@2.5.12 || 2.5.15'
  - '@biomejs/cli-linux-x64@2.5.12 || 2.5.15'
  - '@biomejs/cli-win32-arm64@2.5.12 || 2.5.15'
  - '@biomejs/cli-win32-x64@2.5.12 || 2.5.15'
  - '@vitest/coverage-v8@5.0.0 || 5.0.3'
  - '@vitest/mocker@5.0.0 || 5.0.3'
  - '@vitest/pretty-format@5.0.0 || 5.0.3'
  - '@vitest/spy@5.0.0 || 5.0.3'
  - '@vitest/ui@5.0.0 || 5.0.3'
  - '@vitest/utils@5.0.0 || 5.0.3'
  - vitest@5.0.0 || 5.0.3
  - rolldown-plugin-dts@0.28.5
  - tsdown@0.23.0
  - msw@3.0.1
  - '@types/node@26.6.4'
  - publint@0.3.25
  - satori@0.35.0
