/**
 * Endpoints of the PokéAPI
 */
export enum Endpoints {
  Berry = "/berry",
  BerryFirmness = "/berry-firmness",
  BerryFlavor = "/berry-flavor",
  ContestType = "/contest-type",
  ContestEffect = "/contest-effect",
  SuperContestEffect = "/super-contest-effect",
  EncouterMethod = "/encounter-method",
  EncounterCondition = "/encounter-condition",
  EncouterConditionValue = "/encounter-condition-value",
  EvolutionChain = "/evolution-chain",
  EvolutionTrigger = "/evolution-trigger",
  Generation = "/generation",
  Pokedex = "/pokedex",
  Version = "/version",
  VersionGroup = "/version-group",
  Item = "/item",
  ItemAttribute = "/item-attribute",
  ItemCategory = "/item-category",
  ItemFlingEffect = "/item-fling-effect",
  ItemPocket = "/item-pocket",
  Location = "/location",
  LocationArea = "/location-area",
  PalParkArea = "/pal-park-area",
  Region = "/region",
  Machine = "/machine",
  Move = "/move",
  MoveAilment = "/move-ailment",
  MoveBattleStyle = "/move-battle-style",
  MoveCategory = "/move-category",
  MoveDamageClass = "/move-damage-class",
  MoveLearnMethod = "/move-learn-method",
  MoveTarget = "/move-target",
  Ability = "/ability",
  Characteristic = "/characteristic",
  EggGroup = "/egg-group",
  Gender = "/gender",
  GrowthRate = "/growth-rate",
  Nature = "/nature",
  PokeathlonStat = "/pokeathlon-stat",
  Pokemon = "/pokemon",
  PokemonLocationArea = "/pokemon/:id/encounters",
  PokemonColor = "/pokemon-color",
  PokemonForm = "/pokemon-form",
  PokemonHabitat = "/pokemon-habitat",
  PokemonShape = "/pokemon-shape",
  PokemonSpecies = "/pokemon-species",
  Stat = "/stat",
  Type = "/type",
  Language = "/language",
}
