code --install-extension christian-kohler.path-intellisense &&
code --install-extension codezombiech.gitignore &&
code --install-extension dbaeumer.vscode-eslint &&
code --install-extension eamodio.gitlens &&
code --install-extension EditorConfig.EditorConfig &&
code --install-extension eg2.vscode-npm-script &&
code --install-extension mikestead.dotenv &&
code --install-extension ms-vscode.cpptools &&
code --install-extension redhat.vscode-yaml &&
code --install-extension xabikos.JavaScriptSnippets &&
