#!/bin/sh
# Husky pre-commit hook to check commit messages using commitlint.

# Load Husky
. "$(dirname "$0")/_/husky.sh"

# Display a message indicating that commit message check is in progress
echo "Checking commit message..."

# Run commitlint with the provided commit message
pnpm commitlint --edit $1 -v

# Check the exit status of the previous command
if [ $? -ne 0 ]; then
  echo "Commit message check failed. Please follow the commit message conventions."
  exit 1
else
  echo "Commit message check passed. Proceeding with the commit."
fi
