#!/usr/bin/env sh
# Husky pre-commit hook to run lint-staged using pnpm.

# Load Husky
. "$(dirname -- "$0")/_/husky.sh"

# Display a message indicating that lint-staged is running
echo "Running lint-staged..."

# Run lint-staged with pnpm
pnpm lint-staged

# Check the exit status of the previous command
if [ $? -ne 0 ]; then
  echo "lint-staged check failed. Please fix the issues before committing."
  exit 1
else
  echo "lint-staged check passed. Proceeding with the commit."
fi
