name: Release

on:
  push:
    branches: [main]

concurrency:
  group: release
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  release-please:
    name: Release PR
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release-created: ${{ steps.release.outputs.release_created }}
      tag-name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: release

  publish:
    name: Publish to npm
    needs: release-please
    if: ${{ needs.release-please.outputs.release-created == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          ref: ${{ needs.release-please.outputs.tag-name }}

      - uses: ./.github/actions/setup

      - name: Ensure npm supports trusted publishing
        run: npm install -g npm@12.0.2 --ignore-scripts

      - name: Publish
        run: npm publish
